import json

reason_or_not = {
    "direct": [
        "type_a_what_1",
        "type_a_what_2",
        "type_a_what_3",
        "type_a_what_4",
        "type_a_what_5",
        "type_a_what_6",
        "type_a_what_7",
        "type_a_what_8",
        "type_a_what_9",
        "type_a_what_10",
        "type_a_what_11",
        "type_a_what_12",
        "type_a_what_13",
        "type_a_what_14",
        "type_a_what_15",
        "type_a_what_16",
        "type_a_what_17",
        "type_a_what_18",
        "type_a_what_19",
        "type_a_what_20",
    ],
    "change": [
        "type_d_why_1",
        "type_d_why_2",
        "type_d_why_3",
        "type_d_why_4",
        "type_d_why_5",
        "type_d_why_6",
        "type_d_why_7",
        "type_d_why_8",
        "type_d_why_9",
        "type_d_why_10",
        "type_d_why_11",
        "type_d_why_12",
        "type_d_why_13",
        "type_d_why_14",
        "type_d_why_15",
        "type_d_why_16",
        "type_d_whether_1",
        "type_d_whether_2",
        "type_d_whether_3",
        "type_d_whether_4",
        "type_d_whether_5",
        "type_d_whether_6",
        "type_d_whether_7",
        "type_d_whether_8",
        "type_d_whether_9",
        "type_d_whether_10",
        "type_d_whether_11",
        "type_d_whether_12",
        "type_d_whether_13",
        "type_d_whether_14",
        "type_d_whether_15",
        "type_d_whether_16",
    ],
    "mutual_influence": [
        "type_c_how_1",
        "type_c_how_2",
        "type_c_how_3",
        "type_c_how_4",
        "type_c_how_5",
        "type_c_how_6",
        "type_c_how_7",
        "type_c_how_8",
        "type_c_how_9",
        "type_c_how_10",
        "type_c_how_11",
        "type_c_how_12",
        "type_c_how_13",
        "type_c_how_14",
        "type_c_how_15",
    ],
}

def analysis(model,information_level):
    path=f"synthesize_data/script/data/all_scripts_analysis/{model}_{information_level}_accuracy_error.json"